export const pair=(ar,en)=>({ar,en});
export const business={name:pair('الماهر','Al Maher'),phone:'+962778842130',whatsapp:'https://wa.me/962778842130',address:pair('لواء الرصيفة · جبل الشمالي · شارع الملك عبدالله الثاني، الأردن','Russeifa · Jabal Al Shamali · King Abdullah II Street, Jordan')};
export const photos={hero:'assets/cleaning-hero.webp',sofa:'assets/cleaning-sofa.webp',office:'assets/cleaning-office.webp',glass:'assets/cleaning-glass.webp'};
export const services=[
{id:'home',icon:'home',title:pair('تنظيف المنازل والشقق','Home & apartment cleaning'),description:pair('عناية شاملة بالشقق المفروشة والمنازل والفلل، من الغرف إلى المطابخ.','Complete care for furnished apartments, homes and villas, from rooms to kitchens.'),image:photos.hero},
{id:'sofa',icon:'sofa',title:pair('دراي كلين الكنب والسجاد','Sofa & carpet cleaning'),description:pair('تنظيف الكنب والسجاد والمفروشات لإطلالة منتعشة ومكان أريح.','Refresh sofas, carpets and upholstery for a more comfortable space.'),image:photos.sofa},
{id:'construction',icon:'building',title:pair('تنظيف ما بعد البناء','Post-construction cleaning'),description:pair('إزالة آثار أعمال البناء والتشطيب وتجهيز المكان لبداية جديدة.','Clear away the traces of building and finishing work for a fresh start.'),image:photos.hero},
{id:'glass',icon:'window',title:pair('تنظيف الزجاج والشبابيك','Window & glass cleaning'),description:pair('عناية بالزجاج والشبابيك لإطلالة صافية ولمعان يكمّل نظافة المكان.','Care for windows and glass for a clear view and a polished finish.'),image:photos.glass},
{id:'deep',icon:'shield',title:pair('التنظيف العميق','Deep cleaning'),description:pair('اهتمام بالتفاصيل في المطابخ والزوايا والمساحات التي تحتاج عناية إضافية.','Extra attention for kitchens, corners and areas that need a deeper clean.'),image:photos.hero},
{id:'office',icon:'building',title:pair('تنظيف المكاتب والشركات','Office & business cleaning'),description:pair('مساحات عمل نظيفة ومرتبة، بخدمة تتناسب مع احتياجات منشأتك.','Clean, welcoming workplaces with a service tailored to your business.'),image:photos.office}
];
export const offers=[{id:'carpets',title:pair('أربع سجادات… والخامسة علينا','Four carpets. The fifth is on us.'),description:pair('عرض مذكور في الموقع الحالي. يُرجى التأكد من توفره قبل الحجز.','Offer listed on the existing website. Please confirm availability before booking.'),terms:pair('تنظيف السجادة الخامسة مجاناً عند تنظيف أربع سجادات. المقاسات والأهلية بحاجة إلى تأكيد.','Fifth carpet cleaned free when cleaning four carpets. Size restrictions and eligibility need confirmation.'),start:'',end:'',status:'pending'},
{id:'new-home',title:pair('بيت جديد، بداية نظيفة','New home, fresh start'),description:pair('باقات تنظيف للشقق بعد التشطيب والانتقال إلى منزل جديد.','Cleaning packages for post-construction apartments and moving into a new home.'),terms:pair('نطاق العمل والسعر حسب المكان، ويؤكدان قبل الحجز.','Scope and price depend on the space and are agreed before booking.'),start:'',end:'',status:'pending'},
{id:'business',title:pair('عناية مستمرة بمكانك','Ongoing care for your space'),description:pair('اسأل عن عروض العملاء المميزين والأسعار الخاصة للمكاتب والشركات.','Ask about loyalty offers and special rates for offices and businesses.'),terms:pair('التوفر والأسعار والشروط بحاجة إلى تأكيد. ليست اشتراكاً إلكترونياً أو نظام نقاط.','Availability, rates and terms require confirmation. Not an online subscription or points programme.'),start:'',end:'',status:'pending'}];
export const reviews=[{id:'review-1',title:pair('عميل تجريبي ٠١','Sample customer 01'),description:pair('«نموذج توضيحي: خدمة مرتبة واهتمام بالتفاصيل.»','“Illustrative example: thoughtful service and attention to detail.”'),status:'sample'},{id:'review-2',title:pair('عميل تجريبي ٠٢','Sample customer 02'),description:pair('«نموذج توضيحي: تنسيق واضح وعناية بالمكان.»','“Illustrative example: clear coordination and care for our space.”'),status:'sample'}];
export const gallery=[{id:'gallery-sofa',service:'sofa',title:pair('عناية بالمفروشات','Upholstery care'),before:photos.sofa,after:photos.sofa,status:'sample'},{id:'gallery-office',service:'office',title:pair('مساحات عمل منتعشة','Fresh workspaces'),before:photos.office,after:photos.office,status:'sample'}];
export const faqs=[
[pair('كيف أعرف السعر؟','How do I get a price?'),pair('أخبرنا بنوع الخدمة ومساحة المكان وأرسل الصور عبر واتساب. نؤكد نطاق العمل والسعر معك قبل التنفيذ.','Tell us the service and size of the space, and send photos via WhatsApp. Scope and price are agreed before work starts.')],
[pair('هل اختيار الموعد يؤكد الحجز؟','Does choosing a time confirm my booking?'),pair('لا. الموعد المفضل هو طلب فقط، ويحتاج إلى تأكيد من فريق الماهر.','No. Your preferred time is a request and needs confirmation from the Al Maher team.')],
[pair('ما مناطق الخدمة؟','Which areas do you cover?'),pair('معلومات الموقع الحالي تشير إلى الرصيفة، الأردن. يرجى التواصل لتأكيد تغطية عنوانك.','The existing website lists Russeifa, Jordan. Please contact the team to confirm coverage for your address.')],
[pair('هل صور الأعمال والتقييمات حقيقية؟','Are the work photos and reviews real?'),pair('الصور توضيحية والتقييمات نماذج تجريبية إلى حين تزويدنا بمحتوى معتمد من الشركة.','Photos are illustrative and reviews are demo samples until approved business content is supplied.')],
[pair('هل تُرسل النماذج في هذا العرض؟','Are requests sent from this demo?'),pair('لا. تتم محاكاة الطلب داخل علامة التبويب فقط. لا يُرسل إلى الشركة ولا يؤكد حجزاً. استخدم واتساب للتواصل الفعلي.','No. Requests are simulated in this tab only. Nothing is sent to the business or confirmed. Use WhatsApp for real enquiries.')]
];
