export const pair=(ar,en)=>({ar,en});
export const business={name:pair('الماهر','Al Maher'),phone:'+962778842130',whatsapp:'https://wa.me/962778842130',address:pair('لواء الرصيفة · جبل الشمالي · شارع الملك عبدالله الثاني، الأردن','Russeifa · Jabal Al Shamali · King Abdullah II Street, Jordan')};
export const photos={
hero:'https://images.pexels.com/photos/6195125/pexels-photo-6195125.jpeg?auto=compress&cs=tinysrgb&w=1800',
sofa:'https://images.pexels.com/photos/6195275/pexels-photo-6195275.jpeg?auto=compress&cs=tinysrgb&w=1600',
office:'https://images.pexels.com/photos/6197108/pexels-photo-6197108.jpeg?auto=compress&cs=tinysrgb&w=1600',
glass:'https://images.pexels.com/photos/6197123/pexels-photo-6197123.jpeg?auto=compress&cs=tinysrgb&w=1600'
};
export const services=[
{id:'home',icon:'home',title:pair('تنظيف المنازل والشقق','Home & apartment cleaning'),description:pair('عناية شاملة بالشقق المفروشة والمنازل والفلل، من الغرف إلى المطابخ.','A complete home-care service for apartments, houses and villas, covering living areas, bedrooms, kitchens and the details that make your space feel fresh, comfortable and ready to enjoy.'),image:photos.hero},
{id:'sofa',icon:'sofa',title:pair('دراي كلين الكنب والسجاد','Sofa & carpet cleaning'),description:pair('تنظيف الكنب والسجاد والمفروشات لإطلالة منتعشة ومكان أريح.','Specialist care for sofas, carpets and upholstery to lift everyday dust and refresh the look and feel of the fabrics you use most.'),image:photos.sofa},
{id:'construction',icon:'building',title:pair('تنظيف ما بعد البناء','Post-construction cleaning'),description:pair('إزالة آثار أعمال البناء والتشطيب وتجهيز المكان لبداية جديدة.','A detailed post-construction clean designed to remove dust and finishing residue and prepare your home, office or property for a clean new beginning.'),image:photos.hero},
{id:'glass',icon:'window',title:pair('تنظيف الزجاج والشبابيك','Window & glass cleaning'),description:pair('عناية بالزجاج والشبابيك لإطلالة صافية ولمعان يكمّل نظافة المكان.','Detailed cleaning for windows, glass panels and visible frames, helping create brighter rooms, clearer views and a polished overall finish.'),image:photos.glass},
{id:'deep',icon:'shield',title:pair('التنظيف العميق','Deep cleaning'),description:pair('اهتمام بالتفاصيل في المطابخ والزوايا والمساحات التي تحتاج عناية إضافية.','A more intensive clean for kitchens, bathrooms, corners, fixtures and high-use areas that need extra time, detail and attention.'),image:photos.hero},
{id:'office',icon:'building',title:pair('تنظيف المكاتب والشركات','Office & business cleaning'),description:pair('مساحات عمل نظيفة ومرتبة، بخدمة تتناسب مع احتياجات منشأتك.','Reliable cleaning for offices and commercial spaces, planned around your workplace needs to help maintain a tidy, welcoming environment for teams and visitors.'),image:photos.office}
];
export const offers=[{id:'carpets',title:pair('أربع سجادات… والخامسة علينا','Four carpets. The fifth is on us.'),description:pair('عرض مذكور في الموقع الحالي. يُرجى التأكد من توفره قبل الحجز.','Offer listed on the existing website. Please confirm availability before booking.'),terms:pair('تنظيف السجادة الخامسة مجاناً عند تنظيف أربع سجادات. المقاسات والأهلية بحاجة إلى تأكيد.','Fifth carpet cleaned free when cleaning four carpets. Size restrictions and eligibility need confirmation.'),start:'',end:'',status:'pending'},
{id:'new-home',title:pair('بيت جديد، بداية نظيفة','New home, fresh start'),description:pair('باقات تنظيف للشقق بعد التشطيب والانتقال إلى منزل جديد.','Cleaning packages for post-construction apartments and moving into a new home.'),terms:pair('نطاق العمل والسعر حسب المكان، ويؤكدان قبل الحجز.','Scope and price depend on the space and are agreed before booking.'),start:'',end:'',status:'pending'},
{id:'business',title:pair('عناية مستمرة بمكانك','Ongoing care for your space'),description:pair('اسأل عن عروض العملاء المميزين والأسعار الخاصة للمكاتب والشركات.','Ask about loyalty offers and special rates for offices and businesses.'),terms:pair('التوفر والأسعار والشروط بحاجة إلى تأكيد. ليست اشتراكاً إلكترونياً أو نظام نقاط.','Availability, rates and terms require confirmation. Not an online subscription or points programme.'),start:'',end:'',status:'pending'}];
export const reviews=[{id:'review-1',title:pair('عميل تجريبي ٠١','Sample customer 01'),description:pair('«نموذج توضيحي: خدمة مرتبة واهتمام بالتفاصيل.»','“Illustrative example: thoughtful service and attention to detail.”'),status:'sample'},{id:'review-2',title:pair('عميل تجريبي ٠٢','Sample customer 02'),description:pair('«نموذج توضيحي: تنسيق واضح وعناية بالمكان.»','“Illustrative example: clear coordination and care for our space.”'),status:'sample'}];
export const gallery=[
{id:'gallery-sofa',service:'sofa',title:pair('عناية بالمفروشات','Upholstery care'),before:'https://images.pexels.com/photos/11018239/pexels-photo-11018239.jpeg?auto=compress&cs=tinysrgb&w=1600',after:'https://images.pexels.com/photos/19866404/pexels-photo-19866404.jpeg?auto=compress&cs=tinysrgb&w=1600',status:'sample'},
{id:'gallery-office',service:'office',title:pair('مساحات عمل منتعشة','Fresh workspaces'),before:'https://images.pexels.com/photos/7005459/pexels-photo-7005459.jpeg?auto=compress&cs=tinysrgb&w=1600',after:'https://images.pexels.com/photos/6782349/pexels-photo-6782349.jpeg?auto=compress&cs=tinysrgb&w=1600',status:'sample'}
];
export const faqs=[
[pair('كيف أعرف السعر؟','How do I get a price?'),pair('أخبرنا بنوع الخدمة ومساحة المكان وأرسل الصور عبر واتساب. نؤكد نطاق العمل والسعر معك قبل التنفيذ.','Tell us the service and size of the space, and send photos via WhatsApp. Scope and price are agreed before work starts.')],
[pair('هل اختيار الموعد يؤكد الحجز؟','Does choosing a time confirm my booking?'),pair('لا. الموعد المفضل هو طلب فقط، ويحتاج إلى تأكيد من فريق الماهر.','No. Your preferred time is a request and needs confirmation from the Al Maher team.')],
[pair('ما مناطق الخدمة؟','Which areas do you cover?'),pair('معلومات الموقع الحالي تشير إلى الرصيفة، الأردن. يرجى التواصل لتأكيد تغطية عنوانك.','The existing website lists Russeifa, Jordan. Please contact the team to confirm coverage for your address.')],
[pair('هل صور الأعمال والتقييمات حقيقية؟','Are the work photos and reviews real?'),pair('الصور توضيحية والتقييمات نماذج تجريبية إلى حين تزويدنا بمحتوى معتمد من الشركة.','Photos are illustrative and reviews are demo samples until approved business content is supplied.')],
[pair('هل تُرسل النماذج في هذا العرض؟','Are requests sent from this demo?'),pair('لا. تتم محاكاة الطلب داخل علامة التبويب فقط. لا يُرسل إلى الشركة ولا يؤكد حجزاً. استخدم واتساب للتواصل الفعلي.','No. Requests are simulated in this tab only. Nothing is sent to the business or confirmed. Use WhatsApp for real enquiries.')],
[pair('ما الذي يجعل خدمة الماهر مختلفة؟','What makes Al Maher different?'),pair('نركز على فهم احتياج المكان أولاً، ثم ننسق الخدمة ونطاق العمل والموعد بوضوح قبل الزيارة. الهدف هو تقديم عناية عملية ومنظمة تناسب المنزل أو مكان العمل.','We start by understanding the space, then clearly coordinate the service, scope and timing before the visit. The aim is practical, organised care suited to your home or workplace.')],
[pair('هل يمكن طلب أكثر من خدمة في نفس الزيارة؟','Can I request more than one service in the same visit?'),pair('نعم، يمكنك ذكر جميع الخدمات التي تحتاجها عند طلب عرض السعر، مثل تنظيف المنزل مع الكنب أو السجاد أو الزجاج. يؤكد الفريق الترتيب المناسب بعد مراجعة التفاصيل.','Yes. You can include all the services you need in one quote request, such as home cleaning together with sofa, carpet or glass care. The team can confirm the best arrangement after reviewing the details.')],
[pair('كيف أجهز المكان قبل فريق التنظيف؟','How should I prepare before the cleaning team arrives?'),pair('يفضل إبعاد الأغراض الشخصية أو الحساسة من مناطق العمل وإخبار الفريق مسبقاً بأي أسطح أو قطع تحتاج عناية خاصة.','It helps to move personal or delicate items away from the work area and tell the team in advance about any surfaces or items needing special care.')],
[pair('هل يمكنني إرسال صور قبل الحصول على السعر؟','Can I send photos before getting a price?'),pair('نعم. الصور تساعد الفريق على فهم مساحة المكان وحالته ونوع الخدمة المطلوبة بشكل أفضل قبل تأكيد النطاق والسعر.','Yes. Photos can help the team better understand the size, condition and type of service required before confirming scope and price.')]
];
