// Design-only browser verification. Run npm run serve first.
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
const server=require('http').createServer((req,res)=>{let file=path.resolve('.'+decodeURIComponent(req.url.split('?')[0]));try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end('Not found')}});
(async()=>{await new Promise(r=>server.listen(8080,'127.0.0.1',r));let executablePath=process.env.CHROME_EXECUTABLE,args=['--no-sandbox','--disable-dev-shm-usage'];if(process.env.CHROMIUM_PACKAGE){const c=(await import(process.env.CHROMIUM_PACKAGE)).default;executablePath=await c.executablePath();args=c.args}const browser=await chromium.launch({headless:true,executablePath,args});const page=await browser.newPage();await page.route('https://**/*',r=>r.abort());const errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.BASE_URL||'http://127.0.0.1:8080/';const pages=['index.html','services.html','service-home.html','service-sofa.html','service-construction.html','service-glass.html','service-deep.html','service-office.html','service-villa.html','service-apartment.html','service-car.html','service-tank.html','service-corporate.html','about.html','gallery.html','offers.html','contact.html','quote.html','booking.html','corporate.html','review.html','faq.html','privacy.html','terms.html','admin.html','campaigns/post-construction-cleaning/','campaigns/sofa-cleaning/','campaigns/villa-cleaning/','campaigns/apartment-cleaning/','campaigns/car-dry-cleaning/','campaigns/water-tank-cleaning/','campaigns/corporate-cleaning-contracts/','services/villa-cleaning/','offers/sofa-cleaning/'];let checks=0;const overflow=[];
for(const width of (process.env.SKIP_MATRIX?[]:[320,375,390,430,768,1024,1440])){await page.setViewportSize({width,height:1000});for(const language of ['ar','en'])for(const file of pages){await page.goto(base+file+'?lang='+language);await page.locator('#main h1').waitFor();assert.equal(await page.locator('html').getAttribute('dir'),language==='ar'?'rtl':'ltr');const extra=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);if(extra>1)overflow.push({width,language,file,extra});assert.equal(await page.locator('#main').innerText().then(t=>/\bdemo\b|\bpreview\b|تجريبي|محاكاة/i.test(t)),false,file+' presentation wording');checks++}}
console.log('Page/width/language checks:',checks);console.log('Overflow:',JSON.stringify(overflow));assert.deepEqual(overflow,[]);
await page.goto(base+'campaigns/sofa-cleaning/?lang=en');await page.locator('.campaign-hero a[href="quote.html?service=sofa"]').click();assert.equal(await page.locator('[name=service]').inputValue(),'sofa');await page.locator('#request-form button[type=submit]').click();assert.ok(await page.locator('#error-name').innerText());await page.locator('[name=name]').fill('Interface test');await page.locator('[name=phone]').fill('+962778842130');await page.locator('[name=address]').fill('Amman');await page.locator('[name=size]').fill('3 seats');await page.locator('[name=details]').fill('Sofa cleaning');await page.locator('[name=consent]').check();await page.locator('#photos').setInputFiles({name:'invalid.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});assert.ok((await page.locator('#file-error').innerText()).includes('JPEG'));await page.locator('#photos').setInputFiles(path.resolve('assets/s1.png'));await page.locator('.photo-preview').waitFor();await page.locator('#request-form button[type=submit]').click();await page.locator('#prepare-request').click();await page.locator('#form-alert').waitFor();assert.ok((await page.locator('#form-alert').innerText()).includes('not been sent'));assert.ok((await page.locator('#form-alert a').getAttribute('href')).startsWith('https://wa.me/962778842130?text='));
await page.locator('footer a[href="admin.html"]').click();await page.locator('[data-admin-tab=requests]').first().click();assert.ok((await page.locator('.admin-list').innerText()).includes('Interface test'));await page.locator('[data-platform-edit]').click();await page.locator('[name=status]').selectOption('contacted');await page.locator('#platform-editor button').click();assert.ok((await page.locator('.admin-list').innerText()).includes('Contacted'));
for(const tab of ['services','prices','offers','promotions','gallery','beforeAfter','reviews','clients','logos','landingPages','campaigns','siteContent','faqs','customers','notifications','settings']){await page.locator(`[data-admin-tab=${tab}]`).click();assert.ok((await page.locator('.admin-content').innerText()).length>20)}
await page.locator('[data-admin-tab=clients]').click();await page.locator('[data-platform-edit]').first().click();await page.locator('[name=title_en]').fill('Updated Client');await page.locator('#platform-editor button').click();assert.ok((await page.locator('.admin-list').innerText()).includes('Updated Client'));
await page.goto(base+'booking.html?lang=en');for(const [name,value] of Object.entries({name:'Booking UI',phone:'+962778842130',address:'Zarqa',size:'100 m2',date:'2099-10-05',time:'10:00'}))await page.locator(`[name=${name}]`).fill(value);await page.locator('[name=service]').selectOption('villa');await page.locator('[name=consent]').check();await page.locator('#request-form button[type=submit]').click();await page.locator('#edit-request').click();assert.equal(await page.locator('[name=name]').inputValue(),'Booking UI');await page.locator('#request-form button[type=submit]').click();await page.locator('#prepare-request').click();await page.locator('#form-alert').waitFor();
await page.goto(base+'review.html?lang=en');await page.locator('[name=name]').fill('Customer');await page.locator('[name=review]').fill('My review');await page.locator('#review-form button').click();assert.ok((await page.locator('#review-result').innerText()).includes('ready to send'));
await page.setViewportSize({width:390,height:844});await page.goto(base+'index.html?lang=ar');await page.locator('.menu-toggle').click();await page.locator('#navigation a[href="services.html"]').click();assert.ok(page.url().includes('services.html'));assert.equal(await page.locator('.mobile-actions a').count(),3);
// Check internal links resolve and download metadata for every static route.
for(const file of pages){await page.goto(base+file+'?lang=en');const links=await page.locator('a[href]').evaluateAll(as=>as.map(a=>a.href));for(const url of new Set(links.filter(u=>u.startsWith(base)&&!u.includes('#')))){const response=await page.request.get(url);assert.equal(response.status(),200,url)}}
fs.mkdirSync('/tmp/maher-review',{recursive:true});for(const [name,file,width,language] of [['home-desktop','index.html',1440,'en'],['home-mobile','index.html',390,'ar'],['campaign','campaigns/sofa-cleaning/',1440,'en'],['admin','admin.html',1440,'en'],['booking','booking.html',390,'ar']]){await page.setViewportSize({width,height:1000});await page.goto(base+file+'?lang='+language);await page.waitForTimeout(600);await page.screenshot({path:'/tmp/maher-review/'+name+'.png',fullPage:true})}assert.deepEqual(errors,[]);console.log('PASS: links, forms, photos, review, navigation, administration, RTL/LTR; no runtime errors');await browser.close();server.close()})().catch(e=>{console.error(e);process.exit(1)});
