from pathlib import Path
from html import escape
pages={'index':('الماهر | خدمات التنظيف والدراي كلين','Al Maher | Cleaning & Dry Cleaning'),'services':('خدماتنا','Our services'),'about':('من نحن','About Al Maher'),'gallery':('أعمالنا','Our work'),'offers':('العروض','Offers'),'contact':('تواصل معنا','Contact'),'quote':('طلب عرض سعر','Request a quote'),'booking':('طلب حجز','Booking request'),'faq':('الأسئلة الشائعة','FAQs'),'privacy':('سياسة الخصوصية','Privacy policy'),'terms':('الشروط والأحكام','Terms and conditions'),'admin':('معاينة الإدارة','Admin preview'),'service':('تفاصيل الخدمة','Service details')}
services={'home':('تنظيف المنازل والشقق','Home & apartment cleaning'),'sofa':('دراي كلين الكنب والسجاد','Sofa & carpet cleaning'),'construction':('تنظيف ما بعد البناء','Post-construction cleaning'),'glass':('تنظيف الزجاج والشبابيك','Window & glass cleaning'),'deep':('التنظيف العميق','Deep cleaning'),'office':('تنظيف المكاتب والشركات','Office & business cleaning')}
pages.update({'service-'+k:v for k,v in services.items()})
base='https://subair71.github.io/al-maher-cleaning/'
for page,(ar,en) in pages.items():
    path=page+'.html'
    # Dev remains noindex until approved. Production deployment updates the canonical origin.
    text=f'''<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#14375c"><meta name="robots" content="noindex,nofollow"><title>{escape(ar)} | الماهر</title><meta name="description" content="{escape(ar)} — الماهر لخدمات التنظيف والدراي كلين في الرصيفة، الأردن."><link rel="canonical" href="{base+path}"><link rel="alternate" hreflang="ar-JO" href="{base+path}?lang=ar"><link rel="alternate" hreflang="en" href="{base+path}?lang=en"><link rel="alternate" hreflang="x-default" href="{base+path}"><link rel="preconnect" href="https://images.pexels.com"><link rel="stylesheet" href="responsive-v3.css"><script type="application/ld+json">{{"@context":"https://schema.org","@type":"LocalBusiness","name":"Al Maher Cleaning & Dry Cleaning","telephone":"+962778842130","address":{{"@type":"PostalAddress","streetAddress":"King Abdullah II Street, Jabal Al Shamali","addressLocality":"Russeifa","addressCountry":"JO"}}}}</script></head><body><div id="app"></div><noscript><main><h1>{escape(ar)}</h1><p>الماهر لخدمات التنظيف والدراي كلين · الرصيفة، الأردن.</p><p>يرجى تفعيل JavaScript لتجربة العرض. Enable JavaScript to use the interactive preview.</p><a href="tel:+962778842130">+962778842130</a><a href="https://wa.me/962778842130">WhatsApp</a></main></noscript><script type="module" src="js/app.js"></script></body></html>'''
    Path(path).write_text(text)
Path('sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>{base}{p}.html</loc></url>\n' for p in pages if p not in ['admin','service','quote','booking'])+'</urlset>')
Path('robots.txt').write_text('# Development preview. Change only for an approved production release.\nUser-agent: *\nDisallow: /\n')
