from pathlib import Path
from html import escape
import json
pages={'index':('الماهر | خدمات التنظيف والدراي كلين','Al Maher | Cleaning & Dry Cleaning'),'services':('خدماتنا','Our services'),'about':('من نحن','About Al Maher'),'gallery':('أعمالنا','Our work'),'offers':('العروض','Offers'),'contact':('تواصل معنا','Contact'),'quote':('طلب عرض سعر','Request a quote'),'booking':('طلب حجز','Booking request'),'faq':('الأسئلة الشائعة','FAQs'),'privacy':('سياسة الخصوصية','Privacy policy'),'terms':('الشروط والأحكام','Terms and conditions'),'admin':('لوحة الإدارة','Admin dashboard'),'service':('تفاصيل الخدمة','Service details'),'corporate':('خدمات وعقود تنظيف الشركات','Corporate & contract cleaning'),'review':('شارك تجربتك','Share your experience'),'landing':('خدمات الماهر','Al Maher services')}
services={'home':('تنظيف المنازل والشقق','Home & apartment cleaning'),'sofa':('دراي كلين الكنب والسجاد','Sofa & carpet cleaning'),'construction':('تنظيف ما بعد البناء','Post-construction cleaning'),'glass':('تنظيف الزجاج والشبابيك','Window & glass cleaning'),'deep':('التنظيف العميق','Deep cleaning'),'office':('تنظيف المكاتب والشركات','Office & business cleaning'),'villa':('تنظيف الفلل','Villa cleaning'),'apartment':('تنظيف الشقق','Apartment cleaning'),'car':('دراي كلين السيارات','Car interior dry cleaning'),'tank':('تنظيف خزانات المياه','Water tank cleaning'),'corporate':('عقود تنظيف الشركات','Corporate cleaning contracts')}
slugs={'post-construction-cleaning':'construction','sofa-cleaning':'sofa','villa-cleaning':'villa','apartment-cleaning':'apartment','car-dry-cleaning':'car','water-tank-cleaning':'tank','corporate-cleaning-contracts':'corporate'}
routes={p+'.html':titles for p,titles in pages.items()}
routes.update({'service-'+k+'.html':v for k,v in services.items()})
routes.update({'campaigns/'+slug+'/index.html':services[key] for slug,key in slugs.items()})
routes['offers/sofa-cleaning/index.html']=services['sofa']
routes['services/villa-cleaning/index.html']=services['villa']
base='https://subair71.github.io/al-maher-cleaning/'
for path,(ar,en) in routes.items():
    relative='../'*(len(Path(path).parts)-1) or './'
    url=base+path.replace('/index.html','/')
    description=ar+' — عناية بالمنازل والأعمال في الرصيفة والزرقاء وعمّان. اطلب عرض سعر أو نسّق موعدك مع الماهر.'
    schema={'@context':'https://schema.org','@type':'LocalBusiness','name':'Al Maher Cleaning & Dry Cleaning','telephone':'+962778842130','address':{'@type':'PostalAddress','addressLocality':'Russeifa','addressCountry':'JO'}}
    text=f'''<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><base href="{relative}"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#14375c"><meta name="robots" content="noindex,nofollow"><title>{escape(ar)} | الماهر</title><meta name="description" content="{escape(description)}"><link rel="canonical" href="{url}"><link rel="alternate" hreflang="ar-JO" href="{url}?lang=ar"><link rel="alternate" hreflang="en" href="{url}?lang=en"><link rel="alternate" hreflang="x-default" href="{url}"><meta property="og:type" content="website"><meta property="og:title" content="{escape(ar)}"><meta property="og:description" content="{escape(description)}"><meta property="og:image" content="{base}assets/cleaning-hero.webp"><meta property="og:url" content="{url}"><meta name="twitter:card" content="summary_large_image"><link rel="preload" href="assets/fonts/dm-sans-400.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="responsive-v3.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head><body><div id="app"></div><noscript><main><h1>{escape(ar)}</h1><p>{escape(description)}</p><a href="services.html">خدماتنا / Our services</a><a href="tel:+962778842130">+962778842130</a><a href="https://wa.me/962778842130">WhatsApp</a></main></noscript><script type="module" src="js/app.js"></script></body></html>'''
    target=Path(path);target.parent.mkdir(parents=True,exist_ok=True);target.write_text(text)
Path('sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>{base}{p.replace("/index.html","/")}</loc></url>\n' for p in routes if p not in ['admin.html','service.html','landing.html'])+'</urlset>')
Path('robots.txt').write_text('# Private client presentation; indexing activates after approved implementation.\nUser-agent: *\nDisallow: /\n')
