import {pair as p,photos} from '../data.js';
import {lang,t,w} from '../i18n.js';
import {repository as db} from '../repository.js';
import {escapeHTML as esc} from '../logic.js';
import {requestStatuses} from './catalog.js';
const tr=(a,b)=>t(p(a,b));
let tab='overview',query='',status='';
const groups=[['العمل اليومي','DAILY OPERATIONS',['overview','requests','bookings','corporate','customers','notifications']],['الموقع والتسويق','WEBSITE & MARKETING',['services','prices','offers','promotions','photos','gallery','beforeAfter','reviews','clients','logos','landingPages','campaigns','siteContent','faqs']],['الإدارة','ADMINISTRATION',['settings']]];
const label=k=>k==='photos'?tr('الصور','Photos'):w(k);
const source=k=>({photos:'gallery',prices:'services',promotions:'offers',beforeAfter:'gallery',logos:'clients'}[k]||k);
const requestKinds=['requests','bookings','corporate'];
function value(item){return t(item.title)||item.name||item.requestId||item.id}
function rows(){return db.list(source(tab)).filter(x=>(!status||x.status===status)&&JSON.stringify(x).toLowerCase().includes(query.toLowerCase()))}
function overview(){const leads=requestKinds.flatMap(k=>db.list(k)),newCount=k=>db.list(k).filter(x=>x.status==='new').length;return `<div class="dashboard-welcome"><div><span class="eyebrow">${tr('كل التفاصيل في مكان واحد','EVERY DETAIL, IN ONE PLACE')}</span><h2>${tr('أهلاً بك في الماهر','Welcome to Al Maher')}</h2><p>${tr('تابع الطلبات، ونسّق العناية القادمة.','Follow your enquiries and plan the next visit.')}</p></div><span class="dashboard-date">${new Intl.DateTimeFormat(lang,{dateStyle:'medium'}).format(new Date())}</span></div><div class="stat-grid">${[[w('requests'),newCount('requests'),'requests'],[w('bookings'),newCount('bookings'),'bookings'],[tr('إجمالي الطلبات','Total leads'),leads.length,'customers'],[tr('بانتظار مراجعة التقييم','Reviews awaiting approval'),db.list('reviews').filter(x=>x.status==='pending').length,'reviews']].map(([label,n,k])=>`<button class="card stat" data-admin-tab="${k}"><small>${label}</small><b>${n.toLocaleString(lang)}</b><span>${tr('عرض التفاصيل','View details')} ↗</span></button>`).join('')}</div><div class="dashboard-panels"><section class="card"><div class="section-head"><h3>${tr('أحدث الطلبات','Recent requests')}</h3><button class="text-button" data-admin-tab="requests">${tr('عرض الكل','View all')}</button></div>${leads.length?leads.slice(-5).reverse().map(x=>`<div class="activity-line"><span><b>${esc(x.name)}</b><small>${esc(t(db.get('services',x.service)?.title))}</small></span><span class="pill">${w(x.status)}</span></div>`).join(''):empty(tr('جاهزون لأول طلب','Ready for the first enquiry'),tr('ستظهر الطلبات هنا عند إضافتها إلى مساحة العمل.','Requests appear here when added to this workspace.'))}</section><section class="card"><h3>${tr('رحلة الطلب','Request journey')}</h3><div class="pipeline">${['new','contacted','confirmed','completed'].map(s=>`<div><span>${w(s)}</span><div class="pipeline-track"><i style="width:${leads.length?leads.filter(x=>x.status===s).length/leads.length*100:0}%"></i></div><b>${leads.filter(x=>x.status===s).length}</b></div>`).join('')}</div></section><section class="card"><h3>${tr('الخدمات الأكثر طلباً','Most requested services')}</h3>${leads.length?db.list('services').map(s=>({s,n:leads.filter(x=>x.service===s.id).length})).filter(x=>x.n).sort((a,b)=>b.n-a.n).slice(0,4).map(({s,n})=>`<div class="activity-line"><span>${esc(t(s.title))}</span><b>${n}</b></div>`).join(''):empty(tr('كل خدمة، فرصة جديدة','Every service, a new opportunity'),tr('يتوفر الترتيب عند وجود طلبات.','The ranking appears once requests are available.'))}</section><section class="card"><h3>${tr('مصادر الحملات','Campaign sources')}</h3>${empty(tr('من الزيارة إلى الطلب','From a visit to an enquiry'),tr('تُعرض نتائج الحملات بعد ربط أدوات القياس. لا توجد بيانات زيارات متصلة حالياً.','Campaign results become available after analytics is connected. No live visitor data is connected.'))}<button class="button outline compact" data-admin-tab="campaigns">${w('campaigns')}</button></section></div>`}
function empty(title,description){return `<div class="workspace-empty"><span aria-hidden="true">◇</span><h3>${title}</h3><p>${description}</p></div>`}
const select=(name,values,current)=>`<select name="${name}">${values.map(v=>`<option value="${v}" ${v===current?'selected':''}>${w(v)}</option>`).join('')}</select>`;
function settings(){return `<div class="card"><span class="eyebrow">${tr('إعدادات المنصة','PLATFORM SETTINGS')}</span><h2>${tr('مهيأة للخطوة التالية','Ready for the next step')}</h2><p>${tr('إعدادات التكامل والأدوار معروضة للتخطيط، وتُفعّل في مرحلة التنفيذ.','Integration and role settings are shown for planning and activate during implementation.')}</p>${[['Google Analytics 4','G-XXXXXXXXXX'],['Google Tag Manager','GTM-XXXXXXX'],['Meta Pixel','Pixel ID'],['Google Ads','AW-XXXXXXXXX'],[tr('خرائط Google','Google Maps'),'Google Maps URL']].map(([label,hint])=>`<label class="settings-row"><span>${label}</span><input placeholder="${hint}" disabled><small>${tr('غير متصل','Not connected')}</small></label>`).join('')}<hr><h3>${tr('أدوار الفريق المستقبلية','Future team roles')}</h3><div class="tag-row">${[['مسؤول رئيسي','Super Admin'],['مدير','Manager'],['تسويق','Marketing'],['دعم العملاء','Customer Support'],['عمليات','Operations']].map(([a,b])=>`<span>${tr(a,b)}</span>`).join('')}</div><p class="fine-print">${tr('الحسابات والصلاحيات والإشعارات الآلية والدفع تُضاف في مرحلة التنفيذ.','Authentication, permissions, automated notifications and payments belong to the implementation phase.')}</p></div>`}
function listing(){const kind=source(tab),readOnly=['customers','notifications'].includes(kind),isRequest=requestKinds.includes(kind);return `<div class="section-head"><div><span class="eyebrow">AL MAHER / ${tr('مساحة العمل','WORKSPACE')}</span><h2>${label(tab)}</h2></div>${!readOnly&&!isRequest?`<button class="button compact" id="platform-add">+ ${w('add')}</button>`:''}</div><div class="admin-filters"><label>${w('search')}<input id="platform-search" type="search" value="${esc(query)}" placeholder="${w('search')}"></label><label>${w('status')}<select id="platform-status"><option value="">${w('all')}</option>${(isRequest?requestStatuses:['published','draft','active','inactive','pending','approved','hidden']).map(s=>`<option value="${s}" ${s===status?'selected':''}>${w(s)}</option>`).join('')}</select></label></div><div id="platform-results">${results()}</div>`}
function results(){const kind=source(tab);return rows().length?`<div class="admin-list">${rows().map(item=>`<article class="card admin-row"><div>${item.image||item.logo?`<img class="admin-thumbnail" src="${esc(item.image||item.logo)}" alt="" loading="lazy">`:''}<b>${esc(value(item))}</b><p>${esc(t(item.description)||item.phone||item.kind||'')}</p><div class="tag-row">${item.status?`<span>${w(item.status)}</span>`:''}${item.category?`<span>${esc(t(item.category))}</span>`:''}${item.attribution?.utm_campaign?`<span>${esc(item.attribution.utm_campaign)}</span>`:''}</div>${kind==='landingPages'?`<a class="text-link" href="${item.id.startsWith('item-')?'landing.html?slug='+encodeURIComponent(item.slug):'campaigns/'+encodeURIComponent(item.slug)+'/'}" data-nav>${tr('فتح الصفحة','Open page')} ↗</a>`:''}</div><div class="row-actions"><button class="button outline compact" data-platform-edit="${esc(item.id)}">${requestKinds.includes(kind)||kind==='customers'?tr('التفاصيل','Details'):w('edit')}</button>${!requestKinds.includes(kind)&&!['customers','notifications'].includes(kind)?`<button class="text-button" data-platform-delete="${esc(item.id)}">${w('delete')}</button>`:''}</div></article>`).join('')}</div>`:empty(tr('مساحة منظمة لكل تفاصيلك','An organised home for every detail'),tr('لا توجد عناصر مطابقة حالياً.','There are no matching items yet.'))}
export function adminPage(){return `<section class="wrap admin-heading"><div><span class="eyebrow">AL MAHER / ${tr('الإدارة','OPERATIONS')}</span><h1>${w('admin')}</h1></div><a href="index.html" data-nav class="button outline compact">${tr('زيارة الموقع','Visit website')} ↗</a></section><div class="wrap workspace-note">${tr('مساحة جلسة مستقلة · التغييرات تبقى في علامة التبويب الحالية فقط. لا توجد بيانات عملاء أو تحليلات مباشرة متصلة.','Session workspace · changes stay in this browser tab only. No live customer database or analytics is connected.')}</div><section class="wrap admin-layout"><aside class="admin-nav">${groups.map(([a,b,ks])=>`<span class="admin-group-label">${tr(a,b)}</span>${ks.map(k=>`<button data-admin-tab="${k}" class="${tab===k?'selected':''}">${label(k)}${requestKinds.includes(k)&&db.list(k).length?`<small>${db.list(k).length}</small>`:''}</button>`).join('')}`).join('')}</aside><div class="admin-content">${tab==='overview'?overview():tab==='settings'?settings():listing()}</div></section>`}
function field(label,name,value='',type='text',required=false){return `<label>${label}${required?' *':''}${type==='textarea'?`<textarea rows="3" name="${name}" maxlength="1500" ${required?'required':''}>${esc(value)}</textarea>`:`<input type="${type}" name="${name}" value="${esc(value)}" maxlength="500" ${required?'required':''}>`}</label>`}
function bilingual(label,key,item,required=false){return field(`${label} · ${tr('العربية','Arabic')}`,key+'_ar',item?.[key]?.ar,'text',required)+field(`${label} · ${tr('الإنجليزية','English')}`,key+'_en',item?.[key]?.en,'text',required)}
function safeImage(v){return !v||/^https:\/\//.test(v)||/^assets\/[\w./-]+$/.test(v)}
export function bindAdmin(render){document.querySelectorAll('[data-admin-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.adminTab;query='';status='';render()});const search=document.querySelector('#platform-search'),filter=document.querySelector('#platform-status');if(search)search.oninput=e=>{query=e.target.value;document.querySelector('#platform-results').innerHTML=results();bindRows(render)};if(filter)filter.onchange=e=>{status=e.target.value;document.querySelector('#platform-results').innerHTML=results();bindRows(render)};const add=document.querySelector('#platform-add');if(add)add.onclick=()=>edit(null,render);bindRows(render)}
function bindRows(render){document.querySelectorAll('[data-platform-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.platformEdit,render));document.querySelectorAll('[data-platform-delete]').forEach(b=>b.onclick=()=>{const dialog=document.querySelector('#editor');dialog.innerHTML=`<h2>${tr('حذف العنصر؟','Delete this item?')}</h2><p>${tr('سيُزال من مساحة الجلسة الحالية.','This removes it from the current session workspace.')}</p><div class="actions"><button class="button" id="platform-confirm">${w('delete')}</button><button class="button outline" id="platform-cancel">${w('cancel')}</button></div>`;dialog.showModal();document.querySelector('#platform-cancel').onclick=()=>dialog.close();document.querySelector('#platform-confirm').onclick=async()=>{await db.remove(source(tab),b.dataset.platformDelete);dialog.close();render()}})}
function edit(id,render){const kind=source(tab),item=id?db.get(kind,id):{},dialog=document.querySelector('#editor'),request=requestKinds.includes(kind),readOnly=['customers','notifications'].includes(kind);let fields='';
 if(request||readOnly){fields=`<dl>${Object.entries(item).filter(([k,v])=>!['photos','attribution','idempotencyKey'].includes(k)&&typeof v!=='object').map(([k,v])=>`<div><dt>${w(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>${item.photos?.length?`<div class="photo-previews">${item.photos.map(f=>`<img src="${esc(f.url)}" alt="${esc(f.name)}">`).join('')}</div>`:''}${item.attribution?`<h3>${tr('مصدر الطلب','Lead attribution')}</h3><dl>${Object.entries(item.attribution).filter(([,v])=>v).map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`:''}`;if(request)fields+=`<label>${w('status')}${select('status',requestStatuses,item.status)}</label>`+field(w('internalNotes'),'internalNotes',item.internalNotes,'textarea');
 }else{
 fields=`<div class="form-grid">${bilingual(tr('العنوان / الاسم','Title / name'),'title',item,true)}${bilingual(tr('الوصف','Description'),'description',item)}`;
 if(['services','landingPages'].includes(kind))fields+=field(tr('الرابط المختصر','URL slug'),'slug',item.slug||'','text',true)+field(tr('رابط الصورة','Image URL'),'image',item.image||photos.hero)+bilingual(tr('عنوان محركات البحث','SEO title'),'seoTitle',item)+bilingual(tr('وصف محركات البحث','SEO description'),'seoDescription',item)+bilingual(tr('مزايا الخدمة (سطر لكل ميزة)','Benefits (one per line)'),'benefits',item);
 if(kind==='services')fields+=bilingual(w('price'),'price',item);
 if(['landingPages','gallery'].includes(kind))fields+=`<label>${w('service')}<select name="service">${db.list('services').map(s=>`<option value="${s.id}" ${s.id===item.service?'selected':''}>${esc(t(s.title))}</option>`).join('')}</select></label>`;
 if(kind==='gallery')fields+=field(tr('صورة قبل','Before image URL'),'before',item.before||photos.sofa)+field(tr('صورة بعد','After image URL'),'after',item.after||photos.sofa);
 if(kind==='clients')fields+=bilingual(tr('الفئة','Category'),'category',item)+field(tr('رابط الشعار','Logo URL'),'logo',item.logo)+field(tr('ترتيب العرض','Display order'),'order',item.order||0,'number');
 if(kind==='offers')fields+=bilingual(tr('الشروط','Terms'),'terms',item)+field(tr('رمز العرض','Coupon code'),'coupon',item.coupon)+field(tr('معلومات الخصم','Discount information'),'discount',item.discount)+field(tr('البداية','Starts'),'start',item.start,'date')+field(tr('النهاية','Ends'),'end',item.end,'date');
 if(kind==='campaigns')fields+=field('UTM source','utm_source',item.utm_source)+field('UTM medium','utm_medium',item.utm_medium)+field('UTM campaign','utm_campaign',item.utm_campaign)+field(tr('رابط صفحة الحملة','Landing URL'),'landingUrl',item.landingUrl);
 if(kind==='reviews')fields+=field(w('rating'),'rating',item.rating||5,'number');
 fields+=`<label>${w('status')}${select('status',kind==='reviews'?['pending','approved','hidden']:kind==='clients'?['sample','active','inactive']:['published','draft'],item.status||'draft')}</label></div>`;
 }
 dialog.innerHTML=`<div class="dialog-head"><h2>${label(tab)} · ${w(id?'edit':'add')}</h2><button id="platform-close" aria-label="${w('close')}">×</button></div><form id="platform-editor">${fields}<p class="error" role="alert" id="platform-error"></p>${!readOnly?`<button class="button">${w('save')}</button>`:''}</form>`;dialog.showModal();document.querySelector('#platform-close').onclick=()=>dialog.close();dialog.querySelectorAll('input,textarea').forEach(i=>{i.oninvalid=()=>i.setCustomValidity(w('required'));i.oninput=()=>i.setCustomValidity('')});document.querySelector('#platform-editor').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget)),next={...item,id:id||'item-'+crypto.randomUUID().slice(0,8)};for(const [key,value] of Object.entries(v)){if(key.endsWith('_ar')||key.endsWith('_en')){const base=key.slice(0,-3);next[base]={...next[base],[key.slice(-2)]:value}}else next[key]=value}if(next.slug&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(next.slug)){document.querySelector('#platform-error').textContent=tr('استخدم حروفاً إنجليزية صغيرة وأرقاماً وشرطات للرابط.','Use lowercase letters, numbers and hyphens for the URL.');return}if(['image','logo','before','after'].some(k=>!safeImage(next[k]))){document.querySelector('#platform-error').textContent=tr('استخدم رابط صورة HTTPS أو مساراً من assets.','Use HTTPS image URLs or an assets path.');return}if(next.start&&next.end&&next.end<next.start){document.querySelector('#platform-error').textContent=tr('تاريخ النهاية يجب أن يلي البداية.','End date must follow start date.');return}if(kind==='reviews'&&(Number(next.rating)<1||Number(next.rating)>5)){document.querySelector('#platform-error').textContent=tr('اختر تقييماً من ١ إلى ٥.','Choose a rating from 1 to 5.');return}if(kind==='services')next.icon=item.icon||'home';await db.save(kind,next);dialog.close();render()};}
