import {pair as p,photos,services,faqs} from '../data.js';
export const extraServices=[
 ['villa','تنظيف الفلل','Villa cleaning','عناية بمساحات الفيلا الداخلية حسب المساحة والأسطح، مع تحديد نطاق العمل قبل الزيارة.','Care for villa interiors, planned around room sizes and surface types, with an agreed scope before the visit.','home'],
 ['apartment','تنظيف الشقق','Apartment cleaning','تنظيف غرف المعيشة والمطابخ والحمامات، قبل الانتقال أو لتجديد راحة المنزل.','Living areas, kitchens and bathrooms, for moving day or a refreshing home clean.','home'],
 ['car','دراي كلين السيارات','Car interior dry cleaning','عناية بمقاعد السيارة والمفروشات الداخلية. يتم تأكيد طريقة التنظيف حسب نوع القماش وحالته.','Care for vehicle seats and interior upholstery. Cleaning methods are confirmed after checking fabric and condition.','sofa'],
 ['tank','تنظيف خزانات المياه','Water tank cleaning','شارك نوع الخزان وسعته وإمكانية الوصول إليه لتحديد الخدمة وطريقة التنفيذ المناسبة.','Share tank type, capacity and access details so the team can confirm a suitable scope and method.','building'],
 ['corporate','عقود تنظيف الشركات','Corporate cleaning contracts','خطط تنظيف للمكاتب والفنادق والمجمعات والمشاريع الكبيرة، تبدأ بمعاينة واحتياجات واضحة.','Cleaning plans for offices, hotels, complexes and large projects, starting with a site assessment and clear requirements.','building']
].map(([id,ar,en,da,de,icon])=>({id,slug:id+'-cleaning',title:p(ar,en),description:p(da,de),icon,image:photos[id==='car'?'sofa':'office'],status:'published',price:p('بعد مراجعة الطلب','Quoted after assessment')}));
export const campaigns=[['construction','post-construction-cleaning'],['sofa','sofa-cleaning'],['villa','villa-cleaning'],['apartment','apartment-cleaning'],['car','car-dry-cleaning'],['tank','water-tank-cleaning'],['corporate','corporate-cleaning-contracts']].map(([service,slug])=>{const s=[...services,...extraServices].find(x=>x.id===service);return {id:slug,slug,service,title:s.title,description:s.description,image:s.image,status:'published',benefits:p('نطاق عمل واضح\nموعد يناسبك\nعناية بالأسطح والممتلكات','Clear agreed scope\nA time that suits you\nCare for surfaces and belongings'),seoTitle:s.title,seoDescription:s.description}});
export const clients=[['01','قطاع الضيافة','Hospitality'],['02','مكاتب وشركات','Offices & companies'],['03','مجمعات سكنية','Residential communities']].map(([id,ar,en],order)=>({id:'client-'+id,title:p('عميل '+id,'Client '+id),category:p(ar,en),description:p('مساحة لشهادة عميل معتمدة عند توفرها.','Space for an approved client testimonial when supplied.'),logo:'',order,status:'sample'}));
export const faqItems=faqs.filter((_,i)=>![3,4].includes(i)).map(([title,description],i)=>({id:'faq-'+i,title,description,status:'published'}));
export const requestStatuses=['new','contacted','quotation_sent','confirmed','scheduled','in_progress','completed','cancelled'];
export const futureModels={customer:['id','name','phone','email','addresses','marketingConsent','createdAt','lastActivity'],job:['id','requestId','teamId','status','scheduledAt','completedAt'],payment:['requestId','paymentStatus','paymentMethod','amount','depositAmount','transactionId'],loyalty:['customerId','points','rewardId'],roles:['super_admin','manager','marketing','support','operations']};
